export const manufacturers: Array<{ value: string; label: string }> = [
    { value: "VinFast", label: "VinFast" },
    { value: "Tesla", label: "Tesla" },
    { value: "BYD", label: "BYD" },
    { value: "BMW", label: "BMW" },
    { value: "Mercedes-Benz", label: "Mercedes-Benz" },
    { value: "Audi", label: "Audi" },
    { value: "Porsche", label: "Porsche" },
    { value: "Hyundai", label: "Hyundai" },
    { value: "Kia", label: "Kia" },
    { value: "Nissan", label: "Nissan" },
    { value: "Toyota", label: "Toyota" },
    { value: "Honda", label: "Honda" },
    { value: "Ford", label: "Ford" },
    { value: "Chevrolet", label: "Chevrolet" },
    { value: "Volkswagen", label: "Volkswagen" },
    { value: "Peugeot", label: "Peugeot" },
    { value: "Volvo", label: "Volvo" },
    { value: "Jaguar", label: "Jaguar" },
] as const;